using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using LiveCharts;
using LiveCharts.Wpf;
using System.IO;
using LiveCharts.Configurations;
using LiveCharts.Defaults;
using Accord.Statistics.Models.Regression.Fitting;
using Accord.Math;
using Accord.Math.Optimization;

namespace OPV_Helper
{
    class PlotClass
    {
        public PlotClass(ReadClass inputTxt, CartesianChart chart,CartesianChart chart1)
        {

            
            double[] Voltage = inputTxt.get_Voltage();
            double[] Power = inputTxt.Get_Power();
            double[] Current =inputTxt.get_Current();
            
            chart.Series = new LiveCharts.SeriesCollection()
{   
    new LineSeries()

    {   
        Opacity =100,
        LineSmoothness=1,
        Title = "Current",
         PointGeometrySize = 7.4,
        PointForeground = Brushes.Gold,
        Fill=null,
        
        
        Values = new ChartValues<ObservablePoint>
        {   new ObservablePoint(Voltage[0],Current[0]),
            new ObservablePoint(Voltage[1],Current[1]),
            new ObservablePoint(Voltage[2],Current[2]),
            new ObservablePoint(Voltage[3],Current[3]),
            new ObservablePoint(Voltage[4],Current[4]),
            new ObservablePoint(Voltage[5],Current[5]),
            new ObservablePoint(Voltage[6],Current[6]),
            new ObservablePoint(Voltage[7],Current[7]),
            new ObservablePoint(Voltage[8],Current[8]),
            new ObservablePoint(Voltage[9],Current[9]),
            new ObservablePoint(Voltage[10],Current[10]),
            new ObservablePoint(Voltage[11],Current[11]),
            new ObservablePoint(Voltage[12],Current[12]),
            new ObservablePoint(Voltage[13],Current[13]),
            new ObservablePoint(Voltage[14],Current[14]),
            new ObservablePoint(Voltage[15],Current[15]),
            new ObservablePoint(Voltage[16],Current[16]),
            new ObservablePoint(Voltage[17],Current[17]),
            new ObservablePoint(Voltage[18],Current[18]),
            new ObservablePoint(Voltage[19],Current[19]),
            new ObservablePoint(Voltage[20],Current[20]),
            new ObservablePoint(Voltage[21],Current[21]),
            new ObservablePoint(Voltage[22],Current[22]),
            new ObservablePoint(Voltage[23],Current[23]),
            new ObservablePoint(Voltage[24],Current[24]),
            new ObservablePoint(Voltage[25],Current[25]),
            new ObservablePoint(Voltage[26],Current[26]),
            new ObservablePoint(Voltage[27],Current[27]),
            new ObservablePoint(Voltage[28],Current[28]),
            new ObservablePoint(Voltage[29],Current[29]),
            new ObservablePoint(Voltage[30],Current[30]),
            new ObservablePoint(Voltage[31],Current[31]),
            new ObservablePoint(Voltage[32],Current[32]),
            new ObservablePoint(Voltage[33],Current[33]),
            new ObservablePoint(Voltage[34],Current[34]),
            new ObservablePoint(Voltage[35],Current[35]),
            new ObservablePoint(Voltage[36],Current[36]),
            new ObservablePoint(Voltage[37],Current[37]),
            new ObservablePoint(Voltage[38],Current[38]),
            new ObservablePoint(Voltage[39],Current[39]),
            new ObservablePoint(Voltage[40],Current[40]),
            new ObservablePoint(Voltage[41],Current[41]),
            new ObservablePoint(Voltage[42],Current[42]),
            new ObservablePoint(Voltage[43],Current[43]),
            new ObservablePoint(Voltage[44],Current[44]),
            new ObservablePoint(Voltage[45],Current[45]),
            new ObservablePoint(Voltage[46],Current[46]),
            new ObservablePoint(Voltage[47],Current[47]),
            new ObservablePoint(Voltage[48],Current[48]),
            new ObservablePoint(Voltage[49],Current[49]),
            new ObservablePoint(Voltage[50],Current[50]),
            new ObservablePoint(Voltage[51],Current[51]),
            new ObservablePoint(Voltage[52],Current[52]),
            new ObservablePoint(Voltage[53],Current[53]),
            new ObservablePoint(Voltage[54],Current[54]),
            new ObservablePoint(Voltage[55],Current[55]),
            new ObservablePoint(Voltage[56],Current[56]),
            new ObservablePoint(Voltage[57],Current[57]),
            new ObservablePoint(Voltage[58],Current[58]),
            new ObservablePoint(Voltage[59],Current[59]),
            new ObservablePoint(Voltage[60],Current[60]),
            new ObservablePoint(Voltage[61],Current[61]),
            new ObservablePoint(Voltage[62],Current[62]),
            new ObservablePoint(Voltage[63],Current[63]),
            new ObservablePoint(Voltage[64],Current[64]),
            new ObservablePoint(Voltage[65],Current[65]),
            new ObservablePoint(Voltage[66],Current[66]),
            new ObservablePoint(Voltage[67],Current[67]),
            new ObservablePoint(Voltage[68],Current[68]),
            new ObservablePoint(Voltage[69],Current[69]),
            new ObservablePoint(Voltage[70],Current[70]),
            new ObservablePoint(Voltage[71],Current[71]),
            new ObservablePoint(Voltage[72],Current[72]),
            new ObservablePoint(Voltage[73],Current[73]),
            new ObservablePoint(Voltage[74],Current[74]),
            new ObservablePoint(Voltage[75],Current[75]),
            new ObservablePoint(Voltage[76],Current[76]),
            new ObservablePoint(Voltage[77],Current[77]),
            new ObservablePoint(Voltage[78],Current[78]),
            new ObservablePoint(Voltage[79],Current[79]),
            new ObservablePoint(Voltage[80],Current[80]),
            new ObservablePoint(Voltage[81],Current[81]),
            new ObservablePoint(Voltage[82],Current[82]),
            new ObservablePoint(Voltage[83],Current[83]),
            new ObservablePoint(Voltage[84],Current[84]),
            new ObservablePoint(Voltage[85],Current[85]),
            new ObservablePoint(Voltage[86],Current[86]),
            new ObservablePoint(Voltage[87],Current[87]),
            new ObservablePoint(Voltage[88],Current[88]),
            new ObservablePoint(Voltage[89],Current[89]),
            new ObservablePoint(Voltage[90],Current[90]),
            new ObservablePoint(Voltage[91],Current[91]),
            new ObservablePoint(Voltage[92],Current[92]),
            new ObservablePoint(Voltage[93],Current[93]),
            new ObservablePoint(Voltage[94],Current[94]),
            new ObservablePoint(Voltage[95],Current[95]),
            new ObservablePoint(Voltage[96],Current[96]),
            new ObservablePoint(Voltage[97],Current[97]),
            new ObservablePoint(Voltage[98],Current[98]),
            new ObservablePoint(Voltage[99],Current[99]),
            new ObservablePoint(Voltage[100],Current[100]),
            new ObservablePoint(Voltage[101],Current[101]),
            new ObservablePoint(Voltage[102],Current[102]),
            new ObservablePoint(Voltage[103],Current[103]),
            new ObservablePoint(Voltage[104],Current[104]),
            new ObservablePoint(Voltage[105],Current[105]),
            new ObservablePoint(Voltage[106],Current[106]),
            new ObservablePoint(Voltage[107],Current[107]),
            new ObservablePoint(Voltage[108],Current[108]),
            new ObservablePoint(Voltage[109],Current[109]),
            new ObservablePoint(Voltage[110],Current[110]),
            new ObservablePoint(Voltage[111],Current[111]),
            new ObservablePoint(Voltage[112],Current[112]),
            new ObservablePoint(Voltage[113],Current[113]),
            new ObservablePoint(Voltage[114],Current[114]),
            new ObservablePoint(Voltage[115],Current[115]),
            new ObservablePoint(Voltage[116],Current[116]),
            new ObservablePoint(Voltage[117],Current[117]),
            new ObservablePoint(Voltage[118],Current[118]),
            new ObservablePoint(Voltage[119],Current[119]),
            new ObservablePoint(Voltage[120],Current[120]),
            new ObservablePoint(Voltage[121],Current[121]),
            new ObservablePoint(Voltage[122],Current[122]),
            new ObservablePoint(Voltage[123],Current[123]),
            new ObservablePoint(Voltage[124],Current[124]),
            new ObservablePoint(Voltage[125],Current[125]),
            new ObservablePoint(Voltage[126],Current[126]),
            new ObservablePoint(Voltage[127],Current[127]),
            new ObservablePoint(Voltage[128],Current[128]),
            new ObservablePoint(Voltage[129],Current[129]),
            new ObservablePoint(Voltage[130],Current[130]),
            new ObservablePoint(Voltage[131],Current[131]),
            new ObservablePoint(Voltage[132],Current[132]),
            new ObservablePoint(Voltage[133],Current[133]),
            new ObservablePoint(Voltage[134],Current[134]),
            new ObservablePoint(Voltage[135],Current[135]),
            new ObservablePoint(Voltage[136],Current[136]),
            new ObservablePoint(Voltage[137],Current[137]),
            new ObservablePoint(Voltage[138],Current[138]),
            new ObservablePoint(Voltage[139],Current[139]),
            new ObservablePoint(Voltage[140],Current[140]),
            new ObservablePoint(Voltage[141],Current[141]),
            new ObservablePoint(Voltage[142],Current[142]),
            new ObservablePoint(Voltage[143],Current[143]),
            new ObservablePoint(Voltage[144],Current[144]),
            new ObservablePoint(Voltage[145],Current[145]),
            new ObservablePoint(Voltage[146],Current[146]),
            new ObservablePoint(Voltage[147],Current[147]),
            new ObservablePoint(Voltage[148],Current[148]),
            new ObservablePoint(Voltage[149],Current[149]),
            new ObservablePoint(Voltage[150],Current[150]),
            new ObservablePoint(Voltage[151],Current[151]),
            new ObservablePoint(Voltage[152],Current[152]),
            new ObservablePoint(Voltage[153],Current[153]),
            new ObservablePoint(Voltage[154],Current[154]),
            new ObservablePoint(Voltage[155],Current[155]),
            new ObservablePoint(Voltage[156],Current[156]),
            new ObservablePoint(Voltage[157],Current[157]),
            new ObservablePoint(Voltage[158],Current[158]),
            new ObservablePoint(Voltage[159],Current[159]),
            new ObservablePoint(Voltage[160],Current[160]),
            new ObservablePoint(Voltage[161],Current[161]),
            new ObservablePoint(Voltage[162],Current[162]),
            new ObservablePoint(Voltage[163],Current[163]),
            new ObservablePoint(Voltage[164],Current[164]),
            new ObservablePoint(Voltage[165],Current[165]),
            new ObservablePoint(Voltage[166],Current[166]),
            new ObservablePoint(Voltage[167],Current[167]),
            new ObservablePoint(Voltage[168],Current[168]),
            new ObservablePoint(Voltage[169],Current[169]),
            new ObservablePoint(Voltage[170],Current[170]),
            new ObservablePoint(Voltage[171],Current[171]),
            new ObservablePoint(Voltage[172],Current[172]),
            new ObservablePoint(Voltage[173],Current[173]),
            new ObservablePoint(Voltage[174],Current[174]),
            new ObservablePoint(Voltage[175],Current[175]),
            new ObservablePoint(Voltage[176],Current[176]),
            new ObservablePoint(Voltage[177],Current[177]),
            new ObservablePoint(Voltage[178],Current[178]),
            new ObservablePoint(Voltage[179],Current[179]),
            new ObservablePoint(Voltage[180],Current[180]),
            new ObservablePoint(Voltage[181],Current[181]),
            new ObservablePoint(Voltage[182],Current[182]),
            new ObservablePoint(Voltage[183],Current[183]),
            new ObservablePoint(Voltage[184],Current[184]),
            new ObservablePoint(Voltage[185],Current[185]),
            new ObservablePoint(Voltage[186],Current[186]),
            new ObservablePoint(Voltage[187],Current[187]),
            new ObservablePoint(Voltage[188],Current[188]),
            new ObservablePoint(Voltage[189],Current[189]),
            new ObservablePoint(Voltage[190],Current[190]),
            new ObservablePoint(Voltage[191],Current[191]),
            new ObservablePoint(Voltage[192],Current[192]),
            new ObservablePoint(Voltage[193],Current[193]),
            new ObservablePoint(Voltage[194],Current[194]),
            new ObservablePoint(Voltage[195],Current[195]),
            new ObservablePoint(Voltage[196],Current[196]),
            new ObservablePoint(Voltage[197],Current[197]),
            new ObservablePoint(Voltage[198],Current[198]),
            new ObservablePoint(Voltage[199],Current[199]),
        }
    }
    };

            chart1.Opacity = 10;
            chart1.Series = new LiveCharts.SeriesCollection()
            {
    new LineSeries()
    {  
        Opacity =100,
        Title = "Power",
        LineSmoothness=1,
        PointGeometrySize = 7.4,
        PointForeground = Brushes.DarkOrange,
        

            Values = new ChartValues<ObservablePoint>
        {
            new ObservablePoint(Voltage[0],Power[0]) ,
            new ObservablePoint(Voltage[1],Power[1]),
            new ObservablePoint(Voltage[2],Power[2]),
            new ObservablePoint(Voltage[3],Power[3]),
            new ObservablePoint(Voltage[4],Power[4]),
            new ObservablePoint(Voltage[5],Power[5]),
            new ObservablePoint(Voltage[6],Power[6]),
            new ObservablePoint(Voltage[7],Power[7]),
            new ObservablePoint(Voltage[8],Power[8]),
            new ObservablePoint(Voltage[9],Power[9]),
            new ObservablePoint(Voltage[10],Power[10]),
            new ObservablePoint(Voltage[11],Power[11]),
            new ObservablePoint(Voltage[12],Power[12]),
            new ObservablePoint(Voltage[13],Power[13]),
            new ObservablePoint(Voltage[14],Power[14]),
            new ObservablePoint(Voltage[15],Power[15]),
            new ObservablePoint(Voltage[16],Power[16]),
            new ObservablePoint(Voltage[17],Power[17]),
            new ObservablePoint(Voltage[18],Power[18]),
            new ObservablePoint(Voltage[19],Power[19]),
            new ObservablePoint(Voltage[20],Power[20]),
            new ObservablePoint(Voltage[21],Power[21]),
            new ObservablePoint(Voltage[22],Power[22]),
            new ObservablePoint(Voltage[23],Power[23]),
            new ObservablePoint(Voltage[24],Power[24]),
            new ObservablePoint(Voltage[25],Power[25]),
            new ObservablePoint(Voltage[26],Power[26]),
            new ObservablePoint(Voltage[27],Power[27]),
            new ObservablePoint(Voltage[28],Power[28]),
            new ObservablePoint(Voltage[29],Power[29]),
            new ObservablePoint(Voltage[30],Power[30]),
            new ObservablePoint(Voltage[31],Power[31]),
            new ObservablePoint(Voltage[32],Power[32]),
            new ObservablePoint(Voltage[33],Power[33]),
            new ObservablePoint(Voltage[34],Power[34]),
            new ObservablePoint(Voltage[35],Power[35]),
            new ObservablePoint(Voltage[36],Power[36]),
            new ObservablePoint(Voltage[37],Power[37]),
            new ObservablePoint(Voltage[38],Power[38]),
            new ObservablePoint(Voltage[39],Power[39]),
            new ObservablePoint(Voltage[40],Power[40]),
             new ObservablePoint(Voltage[41],Power[41]),
            new ObservablePoint(Voltage[42],Power[42]),
            new ObservablePoint(Voltage[43],Power[43]),
            new ObservablePoint(Voltage[44],Power[44]),
            new ObservablePoint(Voltage[45],Power[45]),
            new ObservablePoint(Voltage[46],Power[46]),
            new ObservablePoint(Voltage[47],Power[47]),
            new ObservablePoint(Voltage[48],Power[48]),
            new ObservablePoint(Voltage[49],Power[49]),
            new ObservablePoint(Voltage[50],Power[50]),
            new ObservablePoint(Voltage[51],Power[51]),
            new ObservablePoint(Voltage[52],Power[52]),
            new ObservablePoint(Voltage[53],Power[53]),
            new ObservablePoint(Voltage[54],Power[54]),
            new ObservablePoint(Voltage[55],Power[55]),
            new ObservablePoint(Voltage[56],Power[56]),
            new ObservablePoint(Voltage[57],Power[57]),
            new ObservablePoint(Voltage[58],Power[58]),
            new ObservablePoint(Voltage[59],Power[59]),
            new ObservablePoint(Voltage[60],Power[60]),
            new ObservablePoint(Voltage[61],Power[61]),
            new ObservablePoint(Voltage[62],Power[62]),
            new ObservablePoint(Voltage[63],Power[63]),
            new ObservablePoint(Voltage[64],Power[64]),
            new ObservablePoint(Voltage[65],Power[65]),
            new ObservablePoint(Voltage[66],Power[66]),
            new ObservablePoint(Voltage[67],Power[67]),
            new ObservablePoint(Voltage[68],Power[68]),
            new ObservablePoint(Voltage[69],Power[69]),
            new ObservablePoint(Voltage[70],Power[70]),
            new ObservablePoint(Voltage[71],Power[71]),
            new ObservablePoint(Voltage[72],Power[72]),
            new ObservablePoint(Voltage[73],Power[73]),
            new ObservablePoint(Voltage[74],Power[74]),
            new ObservablePoint(Voltage[75],Power[75]),
            new ObservablePoint(Voltage[76],Power[76]),
            new ObservablePoint(Voltage[77],Power[77]),
            new ObservablePoint(Voltage[78],Power[78]),
            new ObservablePoint(Voltage[79],Power[79]),
            new ObservablePoint(Voltage[80],Power[80]),
            new ObservablePoint(Voltage[81],Power[81]),
            new ObservablePoint(Voltage[82],Power[82]),
            new ObservablePoint(Voltage[83],Power[83]),
            new ObservablePoint(Voltage[84],Power[84]),
            new ObservablePoint(Voltage[85],Power[85]),
            new ObservablePoint(Voltage[86],Power[86]),
            new ObservablePoint(Voltage[87],Power[87]),
            new ObservablePoint(Voltage[88],Power[88]),
            new ObservablePoint(Voltage[89],Power[89]),
            new ObservablePoint(Voltage[90],Power[90]),
            new ObservablePoint(Voltage[91],Power[91]),
            new ObservablePoint(Voltage[92],Power[92]),
            new ObservablePoint(Voltage[93],Power[93]),
            new ObservablePoint(Voltage[94],Power[94]),
            new ObservablePoint(Voltage[95],Power[95]),
            new ObservablePoint(Voltage[96],Power[96]),
            new ObservablePoint(Voltage[97],Power[97]),
            new ObservablePoint(Voltage[98],Power[98]),
            new ObservablePoint(Voltage[99],Power[99]),
            new ObservablePoint(Voltage[100],Power[100]),
            new ObservablePoint(Voltage[101],Power[101]),
            new ObservablePoint(Voltage[102],Power[102]),
            new ObservablePoint(Voltage[103],Power[103]),
            new ObservablePoint(Voltage[104],Power[104]),
            new ObservablePoint(Voltage[105],Power[105]),
            new ObservablePoint(Voltage[106],Power[106]),
            new ObservablePoint(Voltage[107],Power[107]),
            new ObservablePoint(Voltage[108],Power[108]),
            new ObservablePoint(Voltage[109],Power[109]),
            new ObservablePoint(Voltage[110],Power[110]),
            new ObservablePoint(Voltage[111],Power[111]),
            new ObservablePoint(Voltage[112],Power[112]),
            new ObservablePoint(Voltage[113],Power[113]),
            new ObservablePoint(Voltage[114],Power[114]),
            new ObservablePoint(Voltage[115],Power[115]),
            new ObservablePoint(Voltage[116],Power[116]),
            new ObservablePoint(Voltage[117],Power[117]),
            new ObservablePoint(Voltage[118],Power[118]),
            new ObservablePoint(Voltage[119],Power[119]),
            new ObservablePoint(Voltage[120],Power[120]),
            new ObservablePoint(Voltage[121],Power[121]),
            new ObservablePoint(Voltage[122],Power[122]),
            new ObservablePoint(Voltage[123],Power[123]),
            new ObservablePoint(Voltage[124],Power[124]),
            new ObservablePoint(Voltage[125],Power[125]),
            new ObservablePoint(Voltage[126],Power[126]),
            new ObservablePoint(Voltage[127],Power[127]),
            new ObservablePoint(Voltage[128],Power[128]),
            new ObservablePoint(Voltage[129],Power[129]),
            new ObservablePoint(Voltage[130],Power[130]),
            new ObservablePoint(Voltage[131],Power[131]),
            new ObservablePoint(Voltage[132],Power[132]),
            new ObservablePoint(Voltage[133],Power[133]),
            new ObservablePoint(Voltage[134],Power[134]),
            new ObservablePoint(Voltage[135],Power[135]),
            new ObservablePoint(Voltage[136],Power[136]),
            new ObservablePoint(Voltage[137],Power[137]),
            new ObservablePoint(Voltage[138],Power[138]),
            new ObservablePoint(Voltage[139],Power[139]),
            new ObservablePoint(Voltage[140],Power[140]),
            new ObservablePoint(Voltage[141],Power[141]),
            new ObservablePoint(Voltage[142],Power[142]),
            new ObservablePoint(Voltage[143],Power[143]),
            new ObservablePoint(Voltage[144],Power[144]),
            new ObservablePoint(Voltage[145],Power[145]),
            new ObservablePoint(Voltage[146],Power[146]),
            new ObservablePoint(Voltage[147],Power[147]),
            new ObservablePoint(Voltage[148],Power[148]),
            new ObservablePoint(Voltage[149],Power[149]),
            new ObservablePoint(Voltage[150],Power[150]),
            new ObservablePoint(Voltage[151],Power[151]),
            new ObservablePoint(Voltage[152],Power[152]),
            new ObservablePoint(Voltage[153],Power[153]),
            new ObservablePoint(Voltage[154],Power[154]),
            new ObservablePoint(Voltage[155],Power[155]),
            new ObservablePoint(Voltage[156],Power[156]),
            new ObservablePoint(Voltage[157],Power[157]),
            new ObservablePoint(Voltage[158],Power[158]),
            new ObservablePoint(Voltage[159],Power[159]),
            new ObservablePoint(Voltage[160],Power[160]),
            new ObservablePoint(Voltage[161],Power[161]),
            new ObservablePoint(Voltage[162],Power[162]),
            new ObservablePoint(Voltage[163],Power[163]),
            new ObservablePoint(Voltage[164],Power[164]),
            new ObservablePoint(Voltage[165],Power[165]),
            new ObservablePoint(Voltage[166],Power[166]),
            new ObservablePoint(Voltage[167],Power[167]),
            new ObservablePoint(Voltage[168],Power[168]),
            new ObservablePoint(Voltage[169],Power[169]),
            new ObservablePoint(Voltage[170],Power[170]),
            new ObservablePoint(Voltage[171],Power[171]),
            new ObservablePoint(Voltage[172],Power[172]),
            new ObservablePoint(Voltage[173],Power[173]),
            new ObservablePoint(Voltage[174],Power[174]),
            new ObservablePoint(Voltage[175],Power[175]),
            new ObservablePoint(Voltage[176],Power[176]),
            new ObservablePoint(Voltage[177],Power[177]),
            new ObservablePoint(Voltage[178],Power[178]),
            new ObservablePoint(Voltage[179],Power[179]),
            new ObservablePoint(Voltage[180],Power[180]),
             new ObservablePoint(Voltage[181],Power[181]),
            new ObservablePoint(Voltage[182],Power[182]),
            new ObservablePoint(Voltage[183],Power[183]),
            new ObservablePoint(Voltage[184],Power[184]),
            new ObservablePoint(Voltage[185],Power[185]),
            new ObservablePoint(Voltage[186],Power[186]),
            new ObservablePoint(Voltage[187],Power[187]),
            new ObservablePoint(Voltage[188],Power[188]),
            new ObservablePoint(Voltage[189],Power[189]),
            new ObservablePoint(Voltage[190],Power[190]),
            new ObservablePoint(Voltage[191],Power[191]),
            new ObservablePoint(Voltage[192],Power[192]),
            new ObservablePoint(Voltage[193],Power[193]),
            new ObservablePoint(Voltage[194],Power[194]),
            new ObservablePoint(Voltage[195],Power[195]),
            new ObservablePoint(Voltage[196],Power[196]),
            new ObservablePoint(Voltage[197],Power[197]),
            new ObservablePoint(Voltage[198],Power[198]),
            new ObservablePoint(Voltage[199],Power[199]),
        }

            }        
        };
        }

        public SeriesCollection SeriesCollection { get; set; }
        public string[] Labels { get; set; }
        public Func<double, string> YFormatter { get; set; }
    }
   
}

